//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPr1mal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pr1malRegistrosEntities : DbContext
    {
        public Pr1malRegistrosEntities()
            : base("name=Pr1malRegistrosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cstate> cstate { get; set; }
        public virtual DbSet<RegistroClien> RegistroClien { get; set; }
        public virtual DbSet<RegistroEmple> RegistroEmple { get; set; }
    }
}
