//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPr1mal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroEmple
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Namiento { get; set; }
        public string Genero { get; set; }
        public int Edad { get; set; }
        public string Celular { get; set; }
        public string Direccion { get; set; }
        public string Registro { get; set; }
        public string Nip { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public double Altura { get; set; }
        public double Peso { get; set; }
        public double Imc { get; set; }
        public double Corporal { get; set; }
        public int Metabolismo { get; set; }
        public double Grasa { get; set; }
        public double Musculo { get; set; }
        public string Numero { get; set; }
        public string Observciones { get; set; }
        public Nullable<int> idState { get; set; }
    
        public virtual cstate cstate { get; set; }
    }
}
